server:
  env_name: ${APP_ENV:local}

llm:
  mode: llamacpp
  max_new_tokens: 512
  context_window: 3900
  tokenizer: Orbina/Orbita-v0.1
  prompt_style: "default"

llamacpp:
  llm_hf_repo_id: NikolayKozloff/Orbita-v0.1-GGUF
  llm_hf_model_file: orbita-v0.1.Q5_K_M.gguf

embedding:
  mode: huggingface

huggingface:
  embedding_hf_model_name: dbmdz/bert-base-turkish-cased  # BAAI/bge-small-en-v1.5 

vectorstore:
  database: qdrant

qdrant:
  path: local_data/private_gpt/qdrant
